spring.application.name=lms
spring.datasource.url=jdbc:postgresql://localhost:5432/fawrylms
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.dll-auto=update
spring.jpa.show-sql=true