DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'semester_settings'
          AND column_name = 'id'
          AND is_identity = 'NO'
    ) THEN
        ALTER TABLE semester_settings
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END
$$@@

SELECT setval(
    pg_get_serial_sequence('semester_settings', 'id'),
    COALESCE((SELECT MAX(id) FROM semester_settings), 1),
    EXISTS(SELECT 1 FROM semester_settings)
 )@@
